### ISSUE TITLE
💸 [Season 2] 벌금 장부 

### ISSUE THREAD

**Issue by yskim0** [E-DEEP/PapersReview#6]
`발표자 벌금` 5000
`일반 벌금` 2000
최종 벌금합계 ₩ 40,000이므로 1/n인 **₩ 5,000** 배분

|날짜|전세희|김연수|백서인|구재원|신한이|한지수|이유정|류정현|
|---|---|---|---|---|---|---|---|---|
|21.04.08|5000|0|0|0|0|0|2000|2000|
|21.04.15|0|0|0|5000|0|0|0|2000|
|21.04.22|0|2000|0|0|0|0|0|2000|
|21.04.29|0|0|0|0|5000|0|0|2000|
|21.05.06|0|2000|2000|0|2000|0|2000|5000|
|---|---|---|---|---|---|---|---|---|
|벌금 합계|5000|4000|2000|5000|7000|0|4000|13000|
|**보증금 잔액**|**5000**|**6000**|**8000**|**5000**|**3000**|**10000**|**6000**|**-3000**|
|---|---|---|---|---|---|---|---|---|
|정산 후|10,000|11,000|13,000|10,000|8,000|15,000|11,000|2,000|
|최종|0|-1,000|-3,000|0|2,000|-5,000|-1,000|8,000|

최종이 
`0` : 별도 입금 필요하지 않음.
`-` : 반환 금액
`+` : 충전 필요 금액

**Comment by simonezz** [comment]
전세희 4/8 발표 업로드 지각

**Comment by JaywonKoo17** [comment]
구재원 4/14 발표 업로드 지각

**Comment by hannie0615** [comment]
신한이 4/29 발표 업로드 지각

**Comment by hannie0615** [comment]
신한이 5/6 리뷰 업로드 하루 지각입니다ㅜ.ㅜ

**Comment by yskim0** [comment]
|날짜|전세희|김연수|백서인|구재원|신한이|한지수|이유정|류정현|
|---|---|---|---|---|---|---|---|---|
|21.05.27|0|0|2000|0|2000|0|0|0|
|21.06.03|2000|2000|0|5000|5000|0|2000|2000|
|21.06.24|2000|2000|0|2000|2000|0|2000|5000|
|---|---|---|---|---|---|---|---|---|
|벌금 합계|4000|4000|2000|7000|9000|0|4000|7000|

**Comment by simonezz** [comment]
6/2 전세희 리뷰 지각😭

**Comment by hannie0615** [comment]
6/3 발표자료 업로드 지각 입니다!ㅜ
