### ISSUE TITLE
[Season 4] 벌금 장부(by 한지수님)

### ISSUE THREAD

**Issue by simonezz** [E-DEEP/PapersReview#7]
연수님 Season 4 휴식으로 인해 한지수님이 담당하시게 되었습니다!

**Comment by JisuHann** [comment]
`발표자 벌금` 5000
`일반 벌금` 2000

1. 발표자의 발표 자료 및 미발표자의 리뷰는 발표 전날인 수요일까지 업로드(미발표자의 리뷰는 발표자가 취합 후 삭제예정)
2. 피치못한 사정으로 참여가 불가능 할 경우 월요일 전에 통보(발표자 외)
3. 피치못한 사정으로 발표가 불가능 할 경우 일요일 전에 통보(발표자) → 다른 순서가 발표를 넘겨받음
4. 1,2번에 대한 벌금 : 발표자불참시 5000원, 발표불참 2000원 (보증금 10000원)
5. 발표 후 각자 짧게라도 리뷰를 적은 내용을 발표자가 추합(발표 자료 포함)해서 다음날인 목요일까지 깃허브에 올림(ex. 2020-12-30-BERT.md 형식)

- 발표자 명단
   - 10/6 백서인 한지수
   - 10/13 류정현 전세희
   - 10/20 이유정
   - 10/27 전세희 백서인
   - 11/3 한지수 류정현
   - 11/10 이유정 구재원

|날짜|한지수|이유정|류정현|
|---|---|---|---|
|21.10.06|0|2000|2000|
|21.10.13|0|2000|5000|
|21.10.20|0|0|2000|
|21.10.27|0|0|0|
|21.11.03|0|0|0|
